stages:
  - scan
  - analysis

variables:
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
  GIT_DEPTH: "0"

before_script:
  - apk add --no-cache curl unzip openjdk17

sonarqube:
  image: gradle:7.5.1-jdk17
  stage: analysis
  script:
    - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
    - unzip sonar-scanner-cli-5.0.1.3006-linux.zip
    - mv sonar-scanner-* sonar-scanner
    - export PATH=$PATH:$CI_PROJECT_DIR/sonar-scanner/bin
    - sonar-scanner -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_TOKEN
  only:
    - main

zap_scan:
  image: owasp/zap2docker-stable
  stage: scan
  script:
    - zap-baseline.py -t http://web:8080 -r zap-report.html
  allow_failure: true
  artifacts:
    paths:
      - zap-report.html
